# -*- coding: utf-8 -*-
"""5.12 - Pratique.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wrnm62a2t9Q4seH3iEevv_H8p3O25N_U
"""

#1. Utilize o comando ‘input’ para receber ao menos 2 números de entrada do usuário;

#2. Converta os valores recebidos pelo usuário para número inteiro (int) ou ponto flutuante (float);

#3. Implemente ao menos 4 operações matemáticas em seu código;

#4. Adicione um laço de repetição ou uma condicional. Por exemplo: você pode permitir que o usuário escolha qual operação realizar ou criar um loop que permita ao usuário realizar várias operações consecutivas;

#5. Utilize o comando ‘print’ para exibir o resultado da operação matemática.

numUm = input("Digite o primeiro número: ")
numDois= input("Digite o segundo número: ")

numUmConv = int(numUm)
numDoisConv = int (numDois)

soma = numUmConv + numDoisConv
sub = numUmConv - numDoisConv
mult = numUmConv * numDoisConv

while True:
  print("\nOpções disponíveis:")
  print("1. Soma;")
  print("2. Subtração;")
  print("3. Multiplicação;")
  print("4. Divisão;")
  print("5. Encerrar calculadora.")

  escolha = input("\nQual a operação desejada?")

  if escolha == "1":
    print("\nO resultado da soma dos dois números é: ",soma)
  elif escolha =="2":
    print("\nO resultado da subtração do primeiro número pelo segundo número é: ",sub)
  elif escolha =="3":
    print("\nO resultado da multiplicação dos dois números é: ",mult)
  elif escolha =="4":
    if numDoisConv == 0:
      print("\nVocê não pode dividir um número por 0! Escolha outra opção.")
    else:
      div = numUmConv / numDoisConv
      print("\nO resultado da divisão do primeiro número pelo segundo número é: ",div)
  elif escolha =="5":
    print("\nEncerrando calculadora...")
    break
  else: print("\nOpção inválida.")